name: Deploy application website
on: 
  push: 
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: read
  packages: write
  pages: write

jobs: 
  buildSite:
    name: Build application website
    uses: ./.github/workflows/containerization-build-template.yml
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: buildSite

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
