name: Release containerization

permissions:
  contents: read

on: 
  push: 
    tags:
      - "[0-9]+\\.[0-9]+\\.[0-9]+"

jobs: 
  containerization:
    uses: ./.github/workflows/containerization-build-template.yml
    with: 
      release: true
      version: ${{ github.ref_name }}
    secrets: inherit
    permissions:
      contents: read
      packages: write
      pages: write

  deployDocs:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: containerization
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release: 
    if: startsWith(github.ref, 'refs/tags/')
    name: Publish release
    timeout-minutes: 30
    needs: containerization
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          name: ${{ github.ref_name }}-prerelease
          draft: true
          make_latest: false
          prerelease: true
          fail_on_unmatched_files: true
